//
// Created by rim on 10/17/22.
//

#ifndef PROJET_TETRAVEX_THREADPARALLELISMBACKTRACKING_H
#define PROJET_TETRAVEX_THREADPARALLELISMBACKTRACKING_H


class ThreadParallelismBacktracking {

};


#endif //PROJET_TETRAVEX_THREADPARALLELISMBACKTRACKING_H
